name: Code coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  flutter_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Installs flutter and related dependency on this machine
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Installs dependencies
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y lcov && flutter pub get
        working-directory: habit_task_tracker

      # Runs unit test, generate coverage data
      - name: Generate coverage data
        run: flutter test --coverage
        working-directory: habit_task_tracker

      # Upload code coverage report. No token needed for public repos
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: habit_task_tracker/coverage/lcov.info
          flags: unittests
