name: Lint and Test Flutter App

# Run on push or PR to main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flutter_job:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

            # Installs flutter and related dependency on this machine
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      # Fetches proj dependencies from pub
      - name: Install dependencies
        run: flutter pub get
        working-directory: habit_task_tracker

      # Lint Dart code
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
        # --set-exit-if-changed stops execution if the any code is not well formatted
        working-directory: habit_task_tracker

      # Lint and analyze Flutter code. Can be configured using analysis_options.yaml
      - name: Analyze project source
        run: flutter analyze --fatal-warnings
        # --fatal-warnings stops execution if any warnings are found
        working-directory: habit_task_tracker

      # Runs unit test
      - name: Run tests
        run: flutter test
        working-directory: habit_task_tracker
